# Generated by Django 2.2.14 on 2021-06-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210617_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='u_id',
        ),
    ]
