# Generated by Django 2.2.14 on 2021-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_remove_projects_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pictures'),
        ),
    ]
