# Generated by Django 2.2.14 on 2021-06-20 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(default='to-do', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
